robair_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

robair_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel'
  right_wheel: 'right_wheel'
  publish_rate: 50
  pose_covariance_diagonal: [0.1, 0.001, 0.001, 0.001, 0.001, 0.3]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 1.0
  velocity_rolling_window_size: 2

gazebo_ros_control:
  pid_gains:
    left_wheel:
      p: 100.0
    right_wheel:
      p: 100.0

  # Base frame_id
  base_frame_id: body

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true

  # robair hardware provides wheel velocities
  estimate_velocity_from_position: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.1   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # rad/s^2
