<?xml version="1.0"?>
<robot name="robair" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- Laser Scanner -->
  <xacro:include filename="$(find robair_description)/urdf/hokuyo.urdf.xacro" />
  <!-- Wheel -->
  <xacro:include filename="$(find robair_description)/urdf/wheel.urdf.xacro" />
  <!-- Wheel Support -->
  <xacro:include filename="$(find robair_description)/urdf/caster_wheel.urdf.xacro" />

  <!-- ######################### Links ############################### -->

  <!-- robair_body -->
  <xacro:property name="height" value="0.2" />
  <xacro:property name="length" value="0.5" />
  <xacro:property name="width"  value="0.3" />

  <link name="robair_body">
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0" />
      <geometry>
          <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 0.7"/>
      </material>
    </visual>
    <collision>
        <origin xyz="0 0 0.1" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${height}"/>
        </geometry>
    </collision>
  </link>

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheel_vertical_offset" value="0.01" />

  <!-- ROBAIR wheels macros -->
  <xacro:wheel wheel_prefix="right" wheel_length="0.02" wheel_radius="0.5">
    <origin xyz="0 ${0.024 + width/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel wheel_prefix="left" wheel_length="0.02" wheel_radius="0.5">
    <origin xyz="0 ${-0.024-width/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <!-- Caster Wheels -->
  <xacro:caster_wheel prefix="front">
    <origin xyz="${-0.1+length/2} 0 ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:caster_wheel>
  <xacro:caster_wheel prefix="rear">
    <origin xyz="${+0.1-length/2} 0 ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:caster_wheel>

  <!-- ########## Joints ################### -->
  <!-- base_link -->
  <link name="$(arg parent)"></link>

  <joint name="parent_to_robair_body_joint" type="fixed">
    <parent link="$(arg parent)"/>
    <child link="robair_body"/>
    <origin xyz="-0.25 0 -0.22" rpy="0 0 0"/>
  </joint>

  <!-- ### Laser Sensor Activation -->
  <!-- Laser Scanner Placement and Parameters -->
  <xacro:arg name="laser_ust10_parent"  default="$(optenv ROBAIR_UST10_PARENT robair_body)" />
  <xacro:arg name="laser_ust10_topic"   default="$(optenv ROBAIR_UST10_TOPIC /scan)" />
  <xacro:arg name="laser_ust10_xyz"     default="$(optenv ROBAIR_UST10_XYZ 0.2206 0.0 0.0)" />
  <xacro:arg name="laser_ust10_rpy"     default="$(optenv ROBAIR_UST10_RPY 0 0 0)" /> 

  <xacro:hokuyo_ust10_mount topic="$(arg laser_ust10_topic)" prefix="" parent_link="$(arg laser_ust10_parent)">
    <origin xyz="$(arg laser_ust10_xyz)" rpy="$(arg laser_ust10_rpy)" />
  </xacro:hokuyo_ust10_mount>

  <!-- Interface with Gazebo ros control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/robair</robotNamespace>
    </plugin>
  </gazebo>

</robot>