controller_list:
  - name: fake_differntial_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - left_wheel
      - right_wheel
initial:  # Define initial robot poses per group
  - group: differntial_controller
    pose: Default