velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - left_wheel
    - right_wheel
  gains:
    left_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1